# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

builder: html

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: { python: "3.7" }
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install
      - pip install docs/requirements.txt
# # Optionally set the version of Python and requirements required to build your docs
# python:
#   version: 3.7
#   install:
#     - requirements: docs/requirements.txt
