name: Sphinx

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install m2r
        sphinx-apidoc -o docs/source ./flowpipe
    - name: Sphinx Build Html
      run: |
        make html
