name: Sphinx

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Sphinx
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install m2r
        sphinx-apidoc -o docs/source ./flowpipe
    - name: Sphinx Build Html
      run: |
        make html
